models:
  - name: "NV-Embed-v2"
    path: "nvidia/NV-Embed-v2"
  - name: "llama-embed-nemotron-8b"
    path: "nvidia/llama-embed-nemotron-8b"
  - name: "Qwen3-Embedding"
    path: "Qwen/Qwen3-Embedding"
  - name: "Arctic-Embed-L-v2.0"
    path: "Snowflake/snowflake-arctic-embed-l-v2.0"
  - name: "Jina-embeddings-v4"
    path: "jinaai/jina-embeddings-v4"
  - name: "multilingual-e5-large"
    path: "intfloat/multilingual-e5-large"
  - name: "BGE-M3"
    path: "BAAI/bge-m3"
  - name: "nomic-embed-text-v1"
    path: "nomic-ai/nomic-embed-text-v1"
  - name: "Codestral Embed"
    path: "mistralai/Codestral-Embed"
  - name: "leaf-ir"
    path: "leaf-ir"
  - name: "granite-embedding-english-r2"
    path: "ibm/granite-embedding-english-r2"
  - name: "Granite-embedding-278m"
    path: "ibm/granite-embedding-278m"
  - name: "EmbeddingGemma"
    path: "google/EmbeddingGemma"
  - name: "granite-embedding-small"
    path: "ibm/granite-embedding-small"
  - name: "MedCPT-v2"
    path: "ncbi/MedCPT-v2"
tasks:
  - "Retrieval"
  - "Classification"
  - "Clustering"
  - "STS"
